#  ▗▄▄▖ ▗▄▖ ▗▖    ▗▄▖ ▗▄▄▖  ▗▄▄▖
# ▐▌   ▐▌ ▐▌▐▌   ▐▌ ▐▌▐▌ ▐▌▐▌
# ▐▌   ▐▌ ▐▌▐▌   ▐▌ ▐▌▐▛▀▚▖ ▝▀▚▖
# ▝▚▄▄▖▝▚▄▞▘▐▙▄▄▖▝▚▄▞▘▐▌ ▐▌▗▄▄▞▘
#

# credits to https://github.com/mylinuxforwork/dotfiles/blob/main/dotfiles/.config/matugen/templates/hyprland-colors.conf
# this a auto switched colors from material colors
# and matugen wiki https://github.com/InioX/matugen/wiki/Templates-Before-3.0.0

<* for name, value in colors *>
${{name}} = rgba({{value.default.hex_stripped}}ff)
<* endfor *>
