[General]
background=background.png
font="SF Pro Display"
iconFont="Material Symbols Rounded, DankMono Nerd Font, FiraCode Nerd Font, symbols"
fontSize=14
clockFormat=HH:mm
dateFormat=dddd, MMMM d
primary=#87d6bd
on_primary=#00382c
primary_container=#005141
on_primary_container=#a2f2d8
surface=#0f1512
surface_container=#1b211e
surface_container_high=#252b29
surface_container_highest=#303633
on_surface=#dee4e0
on_surface_variant=#bfc9c4
outline=#89938e
outline_variant=#3f4945
error=#ffb4ab
error_container=#93000a
on_error=#690005
