
# ▗▄▄▄  ▗▄▖▗▄▄▄▖▗▄▄▖
# ▐▌  █▐▌ ▐▌ █ ▐▌
# ▐▌  █▐▌ ▐▌ █  ▝▀▚▖
# ▐▙▄▄▀▝▚▄▞▘ █ ▗▄▄▞▘

# Default: monitor=,preferred,auto,auto
monitor = eDP-1, 1920x1080@144, 0x0, 1
monitor = HDMI-A-1, 1920x1080@60, 1920x0, 1

##############
### CONFIG ###
##############

source = config/apps.conf
source = config/autostart.conf
source = config/environment.conf
source = config/general.conf
source = config/keybinds.conf
source = config/colors.conf
source = nvidia.conf

##########################
### YOUR CUSTOM CONFIG ###
##########################

source = custom/apps.conf
source = custom/autostart.conf
source = custom/colors.conf
source = custom/general.conf
source = custom/keybinds.conf
source = custom/environment.conf
