-- Main Hyprland Lua Configuration Entrypoint
-- https://wiki.hypr.land/

hl.config({ autogenerated = false })

require("config.colors")
require("config.apps")
require("config.autostart")
require("config.environment")
require("config.rules")
require("config.general")
require("config.keybinds")
require("nvidia")

-- Load custom configurations with pcall to ensure it doesn't crash if they are absent or empty
pcall(require, "custom.colors")
pcall(require, "custom.apps")
pcall(require, "custom.autostart")
pcall(require, "custom.general")
pcall(require, "custom.keybinds")
pcall(require, "custom.environment")
pcall(require, "custom.rules")
