
# ▗▖  ▗▖▗▖  ▗▖▗▄▄▄▖▗▄▄▄ ▗▄▄▄▖ ▗▄▖
# ▐▛▚▖▐▌▐▌  ▐▌  █  ▐▌  █  █  ▐▌ ▐▌
# ▐▌ ▝▜▌▐▌  ▐▌  █  ▐▌  █  █  ▐▛▀▜▌
# ▐▌  ▐▌ ▝▚▞▘ ▗▄█▄▖▐▙▄▄▀▗▄█▄▖▐▌ ▐▌


# Please See https://wiki.hyprland.org/Nvidia/
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia # Disable this if you have issues with screensharing
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = NVD_BACKEND,direct
