background #101010
foreground #FFFFFF

# Black
color0 #414868
color8 #414868

# Red
color1 #FF8080
color9 #FF8080

# Green
color2  #99FFE4
color10 #99FFE4

# Yellow
color3  #FFC799
color11 #FFCFA8

# Blue
color4  #4bc9ff
color12 #4bc9ff

# Magenta
color5  #a78bfa
color13 #a78bfa

# Cyan
color6  #6DD9FF
color14 #6DD9FF

# White
color7  #FFFFFE
color15 #FFFFFE

# Cursor
cursor #e1ecf7
cursor_text_color #1C1C1E

# Selection highlight
selection_foreground none
selection_background #28344a

# The color for highlighting URLs on mouse-over
url_color #419CFF

# Window borders
active_border_color #419CFF
inactive_border_color #242426
bell_border_color #e0af68

# tab color
tab_bar_background #1C1C1E
active_tab_foreground   #419CFF
active_tab_background   #1C1C1E
active_tab_font_style   bold-italic

# incative tab
inactive_tab_foreground #787c99
inactive_tab_background #1D1F22
inactive_tab_font_style bold

# Title bar
macos_titlebar_color #242426

