#!/bin/sh

# Color
sed -i "32s/.*/theme = themes[1]/g" ~/.config/awesome/rc.lua

# Gtk
sed -i "3s/.*/gtk-icon-theme-name=Tela-light/g" ~/.config/gtk-3.0/settings.ini
sed -i "2s/.*/gtk-theme-name=Gruvbox-Dark-BL-LB/g" ~/.config/gtk-3.0/settings.ini

# Picom
sed -i "7s/.*/shadow-opacity = 0.3;/g" ~/.config/picom/picom.conf

#terminal 
kitty +kitten themes --reload-in=all GruvboxHard

# lock screen
betterlockscreen -u ~/Pictures/Wallpapers/gruvbox/gruv-simplistic-ngo.png --fx blur 0.5