#!/bin/sh

# Color
sed -i "32s/.*/theme = themes[1]/g" ~/.config/awesome/rc.lua

# Gtk
sed -i "2s/.*/gtk-icon-theme-name=Mkos-Big-Sur-Night/g" ~/.config/gtk-3.0/settings.ini
sed -i "4s/.*/gtk-theme-name=WhiteSur-dark/g" ~/.config/gtk-3.0/settings.ini

# Picom
sed -i "7s/.*/shadow-opacity = 0.3;/g" ~/.config/picom/picom.conf

#terminal 
kitty +kitten themes --reload-in=all GruvboxHard