#!/bin/sh

# Color
sed -i "32s/.*/theme = themes[2]/g" ~/.config/awesome/rc.lua

# Gtk
sed -i "3s/.*/gtk-icon-theme-name=Mkos-Big-Sur/g" ~/.config/gtk-3.0/settings.ini
sed -i "2s/.*/gtk-theme-name=Colloid-Light/g" ~/.config/gtk-3.0/settings.ini

# Picom
sed -i "7s/.*/shadow-opacity = 0.05;/g" ~/.config/picom/picom.conf

#terminal 
kitty +kitten themes --reload-in=all Light

# lock screen
betterlockscreen -u ~/Pictures/Wallpapers/light/rose_sky.jpg --fx blur 0.5