[config]

[config.custom_colors]
red = { color = "#f38ba8", blend = true }
green = { color = "#a6e3a1", blend = true }
yellow = { color = "#f9e2af", blend = true }
blue = { color = "#89b4fa", blend = true }
orange = { color = "#fab387", blend = true }
purple = { color = "#cba6f7", blend = true }

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/matugen.conf'
post_hook = 'kitten themes --reload-in=all matugen'

[templates.hypr]
input_path = '~/.config/matugen/templates/hypr-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.vicinae]
input_path = '~/.config/matugen/templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.cava]
input_path = '~/.config/matugen/templates/cava'
output_path = '~/.config/cava/config'
