[config]

[config.custom_colors]
red = { color = "#f38ba8", blend = true }
green = { color = "#a6e3a1", blend = true }
yellow = { color = "#f9e2af", blend = true }
blue = { color = "#89b4fa", blend = true }
orange = { color = "#fab387", blend = true }
purple = { color = "#cba6f7", blend = true }

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/matugen.conf'
post_hook = 'kitten themes --reload-in=all matugen'

[templates.hypr]
input_path = '~/.config/matugen/templates/hypr-colors.lua'
output_path = '~/.config/hypr/config/colors.lua'
post_hook = 'hyprctl reload'

[templates.vicinae]
input_path = '~/.config/matugen/templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = '~/.config/matugen/scripts/gtk-themes-reload'

[templates.qt5tc]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/themes/matugen.conf'
post_hook = 'sed -i "s|color_scheme_path=.*|color_scheme_path=$HOME/.config/qt5ct/themes/matugen.conf|" ~/.config/qt5ct/qt5ct.conf'

[templates.qt6tc]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/themes/matugen.conf'
post_hook = 'sed -i "s|color_scheme_path=.*|color_scheme_path=$HOME/.config/qt6ct/themes/matugen.conf|" ~/.config/qt6ct/qt6ct.conf'

[templates.cava]
input_path = '~/.config/matugen/templates/cava'
output_path = '~/.config/cava/config'

[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian.css'
output_path = '~/Dev/Learn/Notes/Dev/.obsidian/themes/MatugenWallpaper/theme.css'

[templates.zed]
input_path = '~/.config/matugen/templates/zed-colors.json'
output_path = '~/.config/zed/themes/custom-theme.json'

[templates.quickshell]
input_path = '~/.config/matugen/templates/quickshell-colours.json'
output_path = '~/.config/quickshell/settings/colours.json'

[templates.wezterm]
input_path = '~/.config/matugen/templates/wezterm_theme.toml'
output_path = '~/.config/wezterm/colors/matugen_theme.toml'
post_hook = 'touch ~/.config/wezterm/wezterm.lua'

[templates.sddm]
input_path = '~/.config/matugen/templates/sddm-theme.conf'
output_path = '~/.config/sddm/themes/savior/theme.conf'
post_hook = '~/.config/matugen/scripts/sddm-theme-reload'
