import QtQuick
import Quickshell
import Quickshell.Io
import qs.core
import qs.services
pragma Singleton

Singleton {
    id: root

    readonly property bool isHyprland: Compositor.require("hyprland")
    readonly property bool shellBlurEnabled: Config.get("theme.transparency.blur", true)
    readonly property bool windowTransparencyEnabled: Config.get("hyprland.transparency.enabled", false)
    readonly property real windowActiveOpacity: Config.get("hyprland.transparency.activeOpacity", 0.95)
    readonly property real windowInactiveOpacity: Config.get("hyprland.transparency.inactiveOpacity", 0.85)
    readonly property bool windowBlurEnabled: Config.get("hyprland.blur.enabled", true)

    property bool _initialized: false
    property string _lastGenLua: ""
    property string _lastRulesLua: ""
    property string _lastEvalLua: ""

    function syncAll() {
        if (!isHyprland)
            return;

        let active = windowTransparencyEnabled ? Math.max(0.1, Math.min(1.0, windowActiveOpacity)) : 1.0;
        let inactive = windowTransparencyEnabled ? Math.max(0.1, Math.min(1.0, windowInactiveOpacity)) : 1.0;
        let winBlur = windowBlurEnabled;
        let shBlur = shellBlurEnabled;
        let ignoreAlpha = 0.05;

        // 1. Live Hyprland evaluation
        let evalLua = "hl.config({ decoration = { active_opacity = " + active.toFixed(2) + ", inactive_opacity = " + inactive.toFixed(2) + ", blur = { enabled = " + winBlur + " } } }); hl.layer_rule({ name = 'quickshell-blur', match = { namespace = 'quickshell' }, blur = " + shBlur + ", ignore_alpha = " + ignoreAlpha + " })";
        if (evalLua !== root._lastEvalLua) {
            root._lastEvalLua = evalLua;
            Quickshell.execDetached(["hyprctl", "eval", evalLua]);
        }

        // 2. Persist to ~/.config/hypr/custom/general.lua and rules.lua
        let genLua = "-- Generated by Quickshell Theming Settings\nhl.config({\n\tdecoration = {\n\t\tactive_opacity = " + active.toFixed(2) + ",\n\t\tinactive_opacity = " + inactive.toFixed(2) + ",\n\t\tblur = {\n\t\t\tenabled = " + winBlur + ",\n\t\t},\n\t},\n})\n";
        let rulesLua = "-- Generated by Quickshell Theming Settings\nhl.layer_rule({\n\tname = \"quickshell-blur\",\n\tmatch = { namespace = \"quickshell\" },\n\tblur = " + shBlur + ",\n\tignore_alpha = " + ignoreAlpha + ",\n})\n";

        if (genLua === root._lastGenLua && rulesLua === root._lastRulesLua)
            return;

        root._lastGenLua = genLua;
        root._lastRulesLua = rulesLua;

        let homeDir = Quickshell.env("HOME") || "";
        let cmd = "mkdir -p \"" + homeDir + "/.config/hypr/custom\" && " +
                  "printf '%s' '" + genLua.replace(/'/g, "'\\''") + "' > \"" + homeDir + "/.config/hypr/custom/general.lua\" && " +
                  "printf '%s' '" + rulesLua.replace(/'/g, "'\\''") + "' > \"" + homeDir + "/.config/hypr/custom/rules.lua\"";

        if (Quickshell.shellDir) {
            cmd += " && mkdir -p \"" + Quickshell.shellDir + "/../hypr/custom\" 2>/dev/null && " +
                   "cp -f \"" + homeDir + "/.config/hypr/custom/general.lua\" \"" + Quickshell.shellDir + "/../hypr/custom/general.lua\" 2>/dev/null || true && " +
                   "cp -f \"" + homeDir + "/.config/hypr/custom/rules.lua\" \"" + Quickshell.shellDir + "/../hypr/custom/rules.lua\" 2>/dev/null || true";
        }

        Quickshell.execDetached(["sh", "-c", cmd]);
    }

    Timer {
        id: syncDebounceTimer
        interval: 50
        repeat: false
        onTriggered: {
            root.syncAll();
        }
    }

    function queueSync() {
        if (root._initialized) {
            syncDebounceTimer.restart();
        }
    }

    onShellBlurEnabledChanged: queueSync()
    onWindowTransparencyEnabledChanged: queueSync()
    onWindowActiveOpacityChanged: queueSync()
    onWindowInactiveOpacityChanged: queueSync()
    onWindowBlurEnabledChanged: queueSync()

    Component.onCompleted: {
        Qt.callLater(() => {
            root._initialized = true;
            root.syncAll();
        });
    }
}
