# ▗▄▖ ▗▄▄▖ ▗▄▄▖  ▗▄▄▖
# ▐▌ ▐▌▐▌ ▐▌▐▌ ▐▌▐▌
# ▐▛▀▜▌▐▛▀▘ ▐▛▀▘  ▝▀▚▖
# ▐▌ ▐▌▐▌   ▐▌   ▗▄▄▞▘

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun -theme ~/.config/rofi/dark.rasi
