# ▗▄▖ ▗▄▄▖ ▗▄▄▖  ▗▄▄▖
# ▐▌ ▐▌▐▌ ▐▌▐▌ ▐▌▐▌
# ▐▛▀▜▌▐▛▀▘ ▐▛▀▘  ▝▀▚▖
# ▐▌ ▐▌▐▌   ▐▌   ▗▄▄▞▘

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = vicinae open
$screenshot = grim -g "$(slurp -d)" - | wl-copy
